from db.connection import OracleConnection

def criar_tabela_analise_solo():
    with OracleConnection() as connection:
        cursor = connection.cursor()
        cursor.execute("""
            CREATE TABLE analise_solo (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                pH FLOAT,
                umidade FLOAT,
                temperatura FLOAT,
                N FLOAT,
                P FLOAT,
                K FLOAT,
                fertilidade INT
            )
        """)
        connection.commit()
        cursor.close()

def verificar_e_criar_tabela():
    with OracleConnection() as connection:
        cursor = connection.cursor()
        cursor.execute("""
            SELECT COUNT(*) FROM user_tables WHERE table_name = 'ANALISE_SOLO'
        """)
        table_exists = cursor.fetchone()[0] > 0
        if not table_exists:
            criar_tabela_analise_solo()
        cursor.close()

if __name__ == "__main__":
    verificar_e_criar_tabela()